version: '3.8'

services:
  pbfortune:
    build: .
    container_name: pbfortune_app
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
